### ISSUE TITLE
[BUG] glitched user interface on soft x

### ISSUE THREAD

**Issue by BlueStarBRS** [Gibbu/BDThemeEditor#11]
if you deactivate vertical user area on soft x its glitched:
![image](https://user-images.githubusercontent.com/25110093/200723471-ac6c8428-6674-4b65-8069-5d23ef94e690.png)
and yes same for downloaded version on my client but also in the web client
![image](https://user-images.githubusercontent.com/25110093/200723746-55200b3e-5c42-415d-9dbb-05c5bbde6374.png)

**Comment by Gibbu** [comment]
Should be moved to https://github.com/DiscordStyles/SoftX
