### ISSUE TITLE
Uploading an image is stuck on 100%

### ISSUE THREAD

**Issue by Musta-VG** [Gibbu/BDThemeEditor#13]
When I upload an image for the background, user popout, anything, it gets to 100% and then nothing, It doesn't even put the image on.

![firefox_pjFb7l5Uk7](https://user-images.githubusercontent.com/77793061/210097076-a7ac63b5-a5e6-4c95-908d-6108eaa121f5.png)

I refreshed the page and tried again but nope, it still happens.

**Comment by Gibbu** [comment]
Open the Dev Tools with `CTRL` + `SHIFT` + `i`
Go to the "Console" tab and send a screenshot

**Comment by Musta-VG** [comment]
> Open the Dev Tools with `CTRL` + `SHIFT` + `i` Go to the "Console" tab and send a screenshot

![firefox_lFpNny69sX](https://user-images.githubusercontent.com/77793061/210130797-6a0e4f3f-3813-4b81-9a49-a858748e1fef.png)
The error appears immediately after the upload "complete."

**Comment by Gibbu** [comment]
Can you expand that "Immutable" error

**Comment by Musta-VG** [comment]
> Can you expand that "Immutable" error

![firefox_HXUde7DgJJ](https://user-images.githubusercontent.com/77793061/210325141-11c7fd2e-9ebb-4b0d-9271-7ca92201ff02.png)
Sure thing!
Also sorry for being late btw.

**Comment by Gibbu** [comment]
No worries, are you able to send the image you're trying to upload? It might be too big for the Imgur API to handle.

You might need to upload it manually at https://imgur.com/upload

**Comment by Musta-VG** [comment]
Yeah I don't think it's possible.
Last I heard imgur is blocked in my country so I guess I just need to find another image.

**Comment by Musta-VG** [comment]
So, uh, this issue can be closed as not planned since this is a me-caused issue not a big or something lol.

**Comment by Gibbu** [comment]
If you've got another image hosting provider that has a public API, let me know and I'll see what I can do.
