### ISSUE TITLE
Window Tilebar enabled even when disabled on editor.

### ISSUE THREAD

**Issue by DerpDerpingtonIsHere** [Gibbu/BDThemeEditor#18]
The Horizontal server list addon is not functioning correctly. It puts the close, resize and minimize button below the server lists. This is a problem because some actions get put behind the close button and I cannot click them or it will close discord. For instance in the theme repo area it puts the close, resize, and minimize button in front of the escape button shown here https://i.imgur.com/UVsrOBf.gif This plugin used to put the 3 buttons above the horizontal list like usual and it had no issues. Am I doing something wrong and is their something I can toggle when making a custom theme that makes it look like normal? When making the theme it does show the buttons in the correct area as shown here https://i.imgur.com/Y4qilbJ.gif

**Comment by Gibbu** [comment]
Your two links are two completely different configs. One has the Windows Titlebar optional import enabled and the other doesn't.

**Comment by DerpDerpingtonIsHere** [comment]
The one that shows the 3 buttons on top are on the website itself. The one that shows it underneath the horizontal server list is in discord. On the theme editor I don't see anything about tilebar. It's it a discord setting out something?

**Comment by DerpDerpingtonIsHere** [comment]
> Your two links are two completely different configs. One has the Windows Titlebar optional import enabled and the other doesn't.
> 
> And the issue you're displaying isn't with Horizontal Server List but rather a incompatibility between the Windows Titlebar addon and Theme/Plugin Repo plugins

I see what you are talking about but I do not have that option enabled on the editor https://i.imgur.com/L2P6IJJ.gif I am still seeing it underneath the Horizontal server list.

**Comment by Gibbu** [comment]
Oooh, I see the issue. I forgot to remove the Windows Titlebar out of the required imports object array.
Give it a couple minutes to rebuild and it should be good to go.

**Comment by DerpDerpingtonIsHere** [comment]
Okay that problem is fixed! However it is now clear for some reason for instance https://www.youtube.com/watch?v=JwHwIB1EkSU
