### ISSUE TITLE
Add Vencord and third-party import options

### ISSUE THREAD

**Issue by shawny43** [Gibbu/BDThemeEditor#25]
Can we bring support of Vencord and any third-party mods clients for Discord?

Vencord require links to works. If you can do it for us, it's could be less hassle for us to make it works.

**Comment by Gibbu** [comment]
And how do you suppose I do that? I can't magically setup a repo for you with all the necessary options.

But what you can do is copy the contents of the file and paste it into your Vencord CustomCSS Editor.

**Comment by shawny43** [comment]
Add a similar way to Discord uploads by a link. An generative one could help. Most website who generate stuff give a generated link to use it. Image hosting are example of what's generated links could fit. 

Vencord just require links. Maybe this could help a bit. For others clients, i guess you can add an integration between user account and the website.

**Comment by Gibbu** [comment]
Or just do what I suggested. Copy the file contents and paste it into your CustomCSS editor. That way you can edit it manually and not have to setup a repo.

**Comment by Gibbu** [comment]
I've added a "Copy CSS" button to the download modal, which will copy everything except the BetterDiscord meta.
