### ISSUE TITLE
Errors on theme download and copy

### ISSUE THREAD

**Issue by Hex-4** [Gibbu/BDThemeEditor#26]
When the Download Theme button is clicked, a silent error (`Uncaught TypeError: Cannot read properties of undefined (reading 'value')`) is thrown:
![image](https://github.com/Gibbu/BDThemeEditor/assets/121138331/ac384645-67e1-495a-9c91-df5e0fccca78)
This also happens with the Copy CSS button, but with a slightly different error:
![image](https://github.com/Gibbu/BDThemeEditor/assets/121138331/9942a598-1730-49d2-bfa5-c328b860affb)
This also seems to happens with every theme.

**Comment by YamikoCrystal** [comment]
I have trouble with this too
If someone knows how to fix it that would be great

**Comment by Gibbu** [comment]
Fixed.
