### ISSUE TITLE
Error rendering components

### ISSUE THREAD

**Issue by Yami2311** [Gibbu/BDThemeEditor#30]
So I boot up the client today and seemingly its having an issue with the code to render the way its supposed to.
Sorry if this is the wrong place to post this, just thought as I got the code from the editor I might be able to get some answers here.
![image_2023-10-25_154001268](https://github.com/Gibbu/BDThemeEditor/assets/138932668/339516f6-f2b8-4eb3-ad09-4032b74d2cbd)

**Comment by Gibbu** [comment]
This has nothing to do with my editor. It was likely due to the Discord update.
