### ISSUE TITLE
More Theme Editable

### ISSUE THREAD

**Issue by scarcekoi** [Gibbu/BDThemeEditor#45]
Instead of being limited to 20 themes. You should be able to upload your own and all I want is a way to view what changes I'm making in my code. Searching in my discord app to find what I changed IS SOOOOOOOO annoying! I just want to be able to upload a file and it tell me what I changed as a visual.

**Comment by Gibbu** [comment]
I tried doing this ages ago, but since themes don't have a set structure, there's just too much to account for.

**Comment by scarcekoi** [comment]
Ok that's fair. All I wanted it for was to be able to see what certain items did because at the time I didn't know how to find the "container__8ef7e" thing. But I now know! No worry.
